version: '3.9'
services:
  xendit:
    container_name: xendit
    build: .
    ports:
      - 8050:8050
    volumes:
      - .:/app
    depends_on:
      - mongo
    networks:
      - xendit-app

  mongo:
    image: mongo
    container_name: db-mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
   
    volumes:
      - mongo-db:/data/db
    ports:
      - 27017:27017
    networks:
      - xendit-app

  mongo-interface:
    image: mongo-express:latest
    container_name: mongo-gui
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - xendit-app
    
    

volumes:
  mongo-db:

networks:
  xendit-app:
    driver: bridge